"""add_metodo_pagamento_to_pagamentos

Revision ID: 1896aa5418cd
Revises: 096c6185dbfd
Create Date: 2026-05-10 16:02:19.079662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1896aa5418cd'
down_revision: Union[str, Sequence[str], None] = '096c6185dbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('metodo_pagamento', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagamentos', 'metodo_pagamento')
    # ### end Alembic commands ###
